#!/usr/bin/env bash
# setup-env.sh — Auto-detect LAN IP and write .env
# Run once before `make up` or call automatically from prod-up.sh.
# If .env already exists and PUBLIC_HOST is set, skips overwrite (use --force to override).
set -euo pipefail
cd "$(dirname "$0")/.."

FORCE=${1:-}

# ── Detect LAN IP ─────────────────────────────────────────────────────────────
detect_ip() {
  # Try hostname -I (Linux)
  local ip
  ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  if [[ -n "$ip" && "$ip" != "127.0.0.1" ]]; then
    echo "$ip"; return
  fi
  # Try ip route (Linux)
  ip=$(ip route get 8.8.8.8 2>/dev/null | awk '/src/{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
  if [[ -n "$ip" && "$ip" != "127.0.0.1" ]]; then
    echo "$ip"; return
  fi
  # Try macOS
  ip=$(ipconfig getifaddr en0 2>/dev/null || true)
  if [[ -n "$ip" ]]; then
    echo "$ip"; return
  fi
  echo "127.0.0.1"
}

# ── Skip if .env exists and has a non-localhost PUBLIC_HOST ───────────────────
if [[ -f .env && "$FORCE" != "--force" ]]; then
  existing=$(grep -E '^PUBLIC_HOST=' .env 2>/dev/null | cut -d= -f2 | tr -d '[:space:]' || true)
  if [[ -n "$existing" && "$existing" != "127.0.0.1" && "$existing" != "localhost" ]]; then
    echo "[setup-env] .env already has PUBLIC_HOST=$existing — skipping (use --force to overwrite)"
    exit 0
  fi
fi

HOST=$(detect_ip)
PROTO=${PUBLIC_PROTO:-http}
WEB_PORT=${WEB_PORT:-3000}
API_PORT=${API_PORT:-8000}

cat > .env <<EOF
# Auto-generated by scripts/setup-env.sh — $(date '+%Y-%m-%d %H:%M:%S')
# Re-run:  bash scripts/setup-env.sh --force

PUBLIC_HOST=${HOST}
PUBLIC_PROTO=${PROTO}
WEB_PORT=${WEB_PORT}
API_PORT=${API_PORT}

MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-200}
MAX_CAT_CATEGORIES=${MAX_CAT_CATEGORIES:-2000}

# Derived — keep in sync with PUBLIC_HOST/PUBLIC_PROTO/ports above
NEXT_PUBLIC_API_BASE_URL=${PROTO}://${HOST}:${API_PORT}
ALLOWED_ORIGINS=${PROTO}://${HOST}:${WEB_PORT}
EOF

echo "[setup-env] Wrote .env:"
echo "  PUBLIC_HOST              = ${HOST}"
echo "  NEXT_PUBLIC_API_BASE_URL = ${PROTO}://${HOST}:${API_PORT}"
echo "  ALLOWED_ORIGINS          = ${PROTO}://${HOST}:${WEB_PORT}"
